### ISSUE TITLE
Component children

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#107]
**Describe the solution you'd like**
Components (`#[component(_)]`) should be able to have child nodes or props.

## Design

Currently, component functions only accept an optional single parameter (the prop type). With this feature, component functions should allow for an optional second parameter that is the children passed to the component. To prevent ambiguity when the prop type is omitted, the children parameter must also be marked with a `#[slot]` attribute.

### Proposed changes to the `#[component(_)]` attribute macro
The proposed syntax is as follows:
```rust
#[component(MyComponent<G>)]
fn my_component(props: Props, #[slot] children: TemplateResult<G>) -> TemplateResult<G> {
    template! { ... }
}

// Or with props omitted (having type '()')
#[component(MyComponent<G>)]
fn my_component(#[slot] children: TemplateResult<G>) -> TemplateResult<G> {
    template! { ... }
}
```

### Children type and proposed changes to the `template!` macro
The proposed changes to the `template!` macro is as follows:
```rust
template! {
    MyComponent() {
        div
    }
}
```
This will pass a `TemplateResult` representing the `div` element to the component. Other types can be passed as well:
```rust
template! {
    MyComponent() {
        (123u32)
    }
}
```
This will pass a `u32` of value `123u32` to the component.

The macro should not attempt to do any casting of the type passed in.

## Additional information
This will improve the ergonomics of using `Indexed` and `Keyed` utility components. The map function can be passed as the children to reduce the number of props. The syntax would be as follows:
```rust
template! {
    Indexed(IndexedProps { each=my_vec }) {
        (|x| template! {
            p { (x) }
        })
    }
}
```

## Alternatives
Make `children` a field of the property type. This is the design of many other web frameworks such as React and Yew.
This does not fit as well into Rust patterns because Rust does not have structural types. One would therefore need an additional trait to access the child and make constructing components in the `template!` macro more complicated.

**Comment by russellwmy** [comment]
Maybe a huge changes, I agree on making sycamore more into a Rust instead of React or Yew. Can we break the template children as individual macro with designed patterns (traits). So it will not increase the complexity of template macro.

**Comment by lukechu10** [comment]
New plan:
I want to eventually get rid of the `component` attribute macro and make components just functions that return `Template<G>`. This would be more idiomatic in Rust as well as reducing the number of proc-macros.

To make it more ergonomic to pass parameters to components, the `template!` macro will be modified to allow the following new syntax:
```rust
template! {
    Component(prop_1=2) {
        prop2=3
    }
    // or
    Component(prop_1=2, prop2=3)
```
Both syntaxes will mean the same thing.

**Comment by adamthrash** [comment]
Can an example of how to use children in components be added to the documentation? I have the following minimal example (CSS and other parts of the page have been removed):

```rust
use sycamore::prelude::*;

#[component]
pub fn Card<'a, G: Html>(cx: Scope<'a>) -> View<G> {
    view! { cx,
	    div() {}
    }
}

fn main() {
    sycamore::render(|cx| view! { cx,
        Card {
	    p { "Test"}
	}
    });
}
```

This code compiles and displays correctly when `p {"Test"}` is commented out. However, when I try to include a paragraph within my Card component, I get this error.

```
error[E0599]: no method named `children` found for struct `UnitBuilder` in the current scope
  --> src/main.rs:13:27
   |
13 |       sycamore::render(|cx| view! { cx,
   |  ___________________________^
14 | |         Card {
15 | |         p { "Test"}
16 | |     }
17 | |     });
   | |_____^ method not found in `UnitBuilder`
   |
   = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)
   ```
   
   I've tried changing the Card function to accept `Props`, but if that's the solution, I'm not able to figure out how to implement it correctly.

**Comment by lukechu10** [comment]
@adamthrash yeah sorry the docs for 0.8 has some missing parts. I'll try to get to it soon.
