### ISSUE TITLE
Scroll back to top of page automatically on navigation

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#121]
Simply call `window.scrollTo(0, 0)` (equivalent using `wasm-bindgen`) after here:
https://github.com/sycamore-rs/sycamore/blob/f3e877b4d9afd423c15c8760edabbbf6ae4a20dd/packages/sycamore-router/src/router.rs#L96-L104
and here:
https://github.com/sycamore-rs/sycamore/blob/f3e877b4d9afd423c15c8760edabbbf6ae4a20dd/packages/sycamore-router/src/router.rs#L142-L146

**Comment by Ochism** [comment]
I would be willing to work on this

**Comment by lukechu10** [comment]
> I would be willing to work on this

Awesome!
