### ISSUE TITLE
Router should not prevent default if meta keys are held down (e.g. `Ctrl + Click`)

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#129]

**Comment by baile320** [comment]
I can help with this one, it seems like there just needs to be a couple ```if``` statements in ```router.rs``` where ```ev.prevent_default()``` is called, and we'll check whether ```let ctrl_key_pressed: bool = ev.clone().unchecked_into::<KeyboardEvent>().meta_key();``` is true/false?

**Comment by lukechu10** [comment]
> I can help with this one, it seems like there just needs to be a couple `if` statements in `router.rs` where `ev.prevent_default()` is called, and we'll check whether `let meta_key_pressed: bool = ev.clone().unchecked_into::<KeyboardEvent>().meta_key();` is true/false?

Go ahead! There are also a few other meta keys which need to be checked for as well: meta, ctrl, shift and alt. The router in SvelteKit might be a good reference:
https://github.com/sveltejs/kit/blob/8854e2ffc48cf653854828f6ac19b2ce620535a6/packages/kit/src/runtime/client/router.js#L103
