### ISSUE TITLE
Shorthand for classes and ids in template!

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#13]
Allow writing:
```rust
template! {
    p.my-class#my-id(attribute=...)
}
```

Which is equivalent to:
```rust
template! {
    p(class="my-class", id="my-id", attribute=...)
}
```

**Comment by Riey** [comment]
I prefer current syntax 

1. rustc doesn't think dash is ident so it might be trickey in macro system and syntax highlighting not works good
2. it seems weird when use variable for class for id

```rust
template! {
    p.(some_string)#(other_id) // ??
}
```

3. IMO most important attribute for html is element tag add something to postfix may hard to read

**Comment by lukechu10** [comment]
> * rustc doesn't think dash is ident so it might be hard to implement in macro system and syntax highlighting not works good
> * it seems weird when use variable for class for id

How about requiring ids and classes to be quoted as string literals:
```rust
template! {
    a."my-class"#"my-id"(href=somewhere)
}
```

In my experience, being able to quickly prefix classes and ids is extremely convenient.
