### ISSUE TITLE
Support query parameters in routes

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#130]

**Comment by Ochism** [comment]
I would be willing to take a look at this.

**Comment by lukechu10** [comment]
Go ahead!

**Comment by davidon-top** [comment]
will make a pr

**Comment by davidon-top** [comment]
@lukechu10 can i rewrite the url segment (parsing, matching) code to work more like proc_macros (tokenstreams, syn/parsing, quote/in this case matching) instead of doing weird string splitting that is hard to get right and has many edge cases

**Comment by lukechu10** [comment]
> @lukechu10 can i rewrite the url segment (parsing, matching) code to work more like proc_macros (tokenstreams, syn/parsing, quote/in this case matching) instead of doing weird string splitting that is hard to get right and has many edge cases

Are you talking about for supporting query parameters? To be honest, I haven’t even really thought about how I would want the API to look. However, I don’t think putting this into the process-macro would be a good idea since in that case you should be using dynamic route paths/segments anyways. 

I was thinking of something more along the lines of SolidJS useSearchParams: https://docs.solidjs.com/solid-router/reference/primitives/use-search-params

what do you think?

**Comment by davidon-top** [comment]
i was starting to work on an implementation that would handle this:
```rust
#[to("/existing/<param>?query=val&match=<capture>&every=<all..>#<frag>")]
```
but simply getting the query and frag from a function in a component would also be fine i guess, it might not be very ssr friendly but once there are first-party server integrations it should be fine
