### ISSUE TITLE
Make `map_indexed` and `map_keyed` more idiomatic

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#151]
Right now, `map_indexed` and `map_keyed` use a lot of index manipulations. This is not very idiomatic in Rust.

Preferably, most of it can be refactored to use iterators instead. This will improve maintainability and perhaps even performance because it will remove the need for bound checks.

**Comment by Cyborus04** [comment]
Can I help with this?

**Comment by lukechu10** [comment]
> Can I help with this?

Go ahead!

**Comment by Cyborus04** [comment]
Okay, this is my first issue, so I wanna make sure I know what I'm supposed to do:

1. Clone the repo
2. Create a new branch
3. Make the changes
4. Commit the changes to the new branch
5. Make a new pull request for that branch to get merged 

Is that right?

**Comment by lukechu10** [comment]
> Okay, this is my first issue, so I wanna make sure I know what I'm supposed to do:
> 
> 1. Clone the repo
> 2. Create a new branch
> 3. Make the changes
> 4. Commit the changes to the new branch
> 5. Make a new pull request for that branch to get merged
> 
> Is that right?

You can simply just click on the `Fork` button on the top right which will create a new repo under your account. You can push your code directly to the `master` branch on that new repo, or, if you want to, create a new branch.
When you create the pull request, click on the `compare across forks` link and select your repo + branch.
If you need any more help, don't hesitate to ask.

**Comment by lukechu10** [comment]
@Cyborus04 are you still working on this? If you need any help, don't hesitate to ask. If you are not working on this anymore, please let me know.

**Comment by Cyborus04** [comment]
Oh sorry! Somehow I didn't see this.

I have been having a bit of difficulty understanding what exactly I'm working on (which I should probably just ask about), plus I have external stuff slowing me down.

I would like to keep working on this, but if you'd rather assign someone else I'll understand

**Comment by lukechu10** [comment]
Basically make the two functions in https://github.com/sycamore-rs/sycamore/blob/master/packages/sycamore-reactive/src/iter.rs more idiomatic.

This is actually a bit harder than I initially thought because the indexes are used everywhere.

**Comment by Cyborus04** [comment]
I just don't fully understand what those functions do. They seem to be modifying the middle section of a vector, but exactly how and in what way I can't quite figure out.

**Comment by lukechu10** [comment]
I can take over if you don't want to work on it anymore. To answer your question, it basically prevents calling the map function for every element when only one element changes. This is because we don't want to create useless dom nodes that will never be used.

**Comment by Cyborus04** [comment]
Ah I'm so sorry to keep you waiting like that!
