### ISSUE TITLE
Enable SSR for documentation website

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#152]
Since the documentation website is hosted on netlify, we can use something like https://github.com/netlify/rust-functions-example to render the website in the serverless function.

**Comment by arctic-hen7** [comment]
@lukechu10 if you wanted, you could also use Perseus to statically render it. I'm happy to help with migrating if needed (the rendering process would probably be similar to that for the Perseus website of taking in Markdown files and rendering docs pages).

**Comment by lukechu10** [comment]
The new docsite now uses SSR!
