### ISSUE TITLE
Remove `format!` calls in `SsrNode`

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#154]
Using `format!` is bad for performance because it pulls in the formatting infrastructure. Instead, replace all instances where `format!` is used with `push` and `push_str`. Also use `String::with_capacity` when possible to avoid unnecessary allocations.

**Comment by rbrishabh** [comment]
I can help with this

**Comment by vishalsodani** [comment]
Seems this issue is still open. I would like to work on this.

**Comment by lukechu10** [comment]
@vishalsodani please, go ahead.

**Comment by vishalsodani** [comment]
@lukechu10 Hi, you have commented here 

> Only files in packages/sycamore/generic_node/ssr_node.rs could use this optimization because they are part of the hot path.

What does this mean? Is there specific usage of `format!` in this file which needs to be replaced?

**Comment by lukechu10** [comment]
@vishalsodani instead of implementing `std::fmt::Display` for the different ssr nodes, create a new function called `write_*` that takes a `&mut String`. Call `.reserve()` on the string with the computed length and then use `.push_str()` or `.push_char()`. This prevents creating an instance of [Arguments](https://doc.rust-lang.org/stable/std/fmt/struct.Arguments.html) which is no always zero-cost. Hopes this helps.
