### ISSUE TITLE
Modifying iterator causes panic when filtered

### ISSUE THREAD

**Issue by Dispersia** [sycamore-rs/sycamore#172]
**Describe the bug**
 Modifying an iterator while it's filtered causes a panic

**To Reproduce**

1. Run todos example
2. Add 2 items (test, test2)
3. Check test2
3. Hit Active
4. Hit Clear completed

**Expected behavior**
The item should be removed from the list, but nothing on the UI should change in this example

**Error**

panicked at 'start is the first index where items[start] != new_items[start]', /sycamore/packages/sycamore/src/rx/iter.rs:69:17

**Environment**

- Sycamore: master
- Browser: firefox

**Comment by lukechu10** [comment]
That's weird. I can't seem to reproduce:

https://user-images.githubusercontent.com/37006668/125987892-c1a1923a-8c61-4a69-b605-fac8913d131e.mp4

(Does the error also happen on the example hosted at https://sycamore-rs.netlify.app/examples/todomvc)

**Comment by Dispersia** [comment]
No, it doesn't happen on that live version, only on cloned master. When was that app updated?

**Comment by lukechu10** [comment]
> No, it doesn't happen on that live version, only on cloned master. When was that app updated?

Hmm. The live version should always reflect the latest master. Do you have the latest commit on your cloned repo? If not, what is it?

**Comment by lukechu10** [comment]
Oh wait, maybe it's because the live version is running in release mode...

**Comment by Dispersia** [comment]
ah ya, it is a debug assert so that's most likely it, good call. I'll be home in just a bit to test

**Comment by lukechu10** [comment]
Just tested it and it only happens in debug mode. Thanks for the bug report!
