### ISSUE TITLE
Setup Minimum Support Rust Version (MSRV)

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#191]
Right now, the latest stable which Sycamore is guaranteed to compile on is Rust 1.53

This should be stated in the documentation and CI tests should be updated to run on 1.53.
Test CI should be run on `[1.53, stable, nightly]` matrix.

`trybuild` ui tests should be locked to run on 1.53

**Comment by tshepang** [comment]
I create #195, but it's without `trybuild`, because I don't understand what that is asking for.

**Comment by Vectornaut** [comment]
Would it be possible to set the [`rust-version`](https://doc.rust-lang.org/cargo/reference/rust-version.html) field so that users can find this out from the compiler, rather than having to notice it in the README?

**Comment by lukechu10** [comment]
> Would it be possible to set the [`rust-version`](https://doc.rust-lang.org/cargo/reference/rust-version.html) field so that users can find this out from the compiler, rather than having to notice it in the README?

Yup that would be a good idea. Probably can go in the workspace manifest. Feel free to send a PR if you want to!

**Comment by Vectornaut** [comment]
> Feel free to send a PR if you want to!

Submitted as pull request #797.
