### ISSUE TITLE
Strip makes nothing render

### ISSUE THREAD

**Issue by Dispersia** [sycamore-rs/sycamore#197]
**Describe the bug**
 Adding any `strip` type to cargo makes nothing happen. No console log, anything

**To Reproduce**
Add
`cargo-features = ["strip"]`
and
`
[profile.release]
strip = "symbols"
`
to Cargo.toml, `trunk serve --release`

**Expected behavior**
Page should render as normal, however console logs shouldn't be super helpful

**Environment**

- Sycamore: master
- Browser: firefox
- OS: windows 10

**Additional context**
I know strip is an experimental feature in Rust, but it happens the same using the normal `strip` utility on *nix, so figure it is still applicable.

I'm going to try and look into it, but if it's not a Sycamore thing, and it's wasm-bindgen or something else, I can move the issue there

**Comment by lukechu10** [comment]
This appears to be some issue either with the new `strip` option or with `wasm-bindgen`. Probably worth opening an issue on their side.

**Comment by Dispersia** [comment]
I didn't see you responded, my bad haha, also posting a year later :P I see that issue and no reason to keep this one open as it's just that
