### ISSUE TITLE
Integration of static assets

### ISSUE THREAD

**Issue by TheSirC** [sycamore-rs/sycamore#208]
Greetings ! Thank you for your hard work !

I am trying to package an application that would like to ship some static assets (`img`, etc) and I do not see anyway to package them with the app : 

1. There is no place for them to be included in the final page : when you try to include them in the dist folder they get erased at the next compile cycle
3. No documentation exist in Sycamore or upstream (Trunk) as far as I could see

Please correct me if I am wrong or let's build the documentation around that (or better if it already exists and I could not find it).

**Comment by lukechu10** [comment]
This page on the trunk docs website should help you: https://trunkrs.dev/assets/
Specifically, the [copy-file](https://trunkrs.dev/assets/#copy-file) and [copy-dir](https://trunkrs.dev/assets/#copy-dir) asset types which will copy files or directories into the `dist` folder as part of the trunk build pipeline.

If this does not solve your issue, please feel free to reopen.
