### ISSUE TITLE
Strings and Interning

### ISSUE THREAD

**Issue by theduke** [sycamore-rs/sycamore#243]
Hi there.

It's great to finally see a JS framework with decent performance numbers in the benchmarks!

I'm also working on a (as of yet private) framework.
String allocation and conversion can take up quite a significant amount of time.

I've stumbled over some observations that might also help sycamore out to become even faster.

I see that you are using `wasm_bindgen::intern` for interning tag names, which certainly helps, but also introduces a lot of `HashMap` lookups on every string creation, so is not necessarily ideal and also doesn't allow the user to manually cache strings. Especially for non-benchmark workloads which have a lot of different strings.

I've started to:
* use a static lookup table for well-known tag/event/attribute names that just store a reusable `JsValue` 
* added a way for the user to (optionally) manually use `JsString`s as attribute values and as content for text nodes, so they can be cached and re-used by the application
  A primary use case for that is classes or styles, since they tend to repeat very often
  That doesn't necessarily show up as a significant factor in small benchmarks, but definitely makes a big difference in larger apps (with potentially thousands of tags with classes, etc)

Since wasm-bindgen doesn't have an API for using `JsString`/`JsValue` here directly, I've added some additional functions to do that:

```rust
/// The `web-sys` crate offers a lot of APIs, but notably there are no setters
/// than can take an existing JS string reference.
/// This prevents improving performance with manual interning of strings, which
/// is a lot of the work being done by DOM creation.
///
/// These manually created Javascript helper functions provide additional
/// setters for common operations and do take existing [`js_sys::JsString`]
/// values.
#[wasm_bindgen::prelude::wasm_bindgen(inline_js = "
export function __brass_elem_set_attr_js_value(elem, attr, value) {
    elem.setAttribute(attr, value);
}

export function __brass_elem_set_attr_str_value(elem, attr, value) {
    elem.setAttribute(attr, value);
}

export function __brass_elem_remove_attr(elem, attr) {
    elem.removeAttribute(attr);
}

export function __brass_create_element(tag) {
    return document.createElement(tag);
}

export function __brass_add_event_listener(elem, event, listener) {
    elem.addEventListener(event, listener);
}
")]
extern "C" {
    fn __brass_elem_set_attr_js_value(
        elem: &web_sys::Element,
        attr: &js_sys::JsString,
        value: &js_sys::JsString,
    );

    fn __brass_elem_set_attr_str_value(
        elem: &web_sys::Element,
        attr: &js_sys::JsString,
        value: &str,
    );

    fn __brass_elem_remove_attr(
        elem: &web_sys::Element,
        attr: &js_sys::JsString,
    );

    fn __brass_create_element(tag: &js_sys::JsString) -> wasm_bindgen::JsValue;

    fn __brass_add_event_listener(
        elem: &web_sys::EventTarget,
        event: &js_sys::JsString,
        listener: &js_sys::Function,
    );
}
```

Might be useful for you to also investigate such optimizations.

**Comment by lukechu10** [comment]
I would prefer not to do this. This seems much too low-level for a higher-level library and I would be very surprised to see a scenario where such optimizations are even needed.
If all string creations were painfully optimized, I doubt there could even be a 10% performance increased as compared to what we have right now. This will obviously not affect the end user experience at all.

**Comment by theduke** [comment]
I've seen significant speedups (> 100%) on string heavy UIs with internal caching.
