### ISSUE TITLE
Support implementing `Route` on `struct`s

### ISSUE THREAD

**Issue by arctic-hen7** [sycamore-rs/sycamore#244]
Currently, Sycamore explicitly states that the `Route` trait is for `enum`s, and as such its method `match_route` doesn't take the `self` parameter. However, there are use-cases (such as [Perseus](https://github.com/arctic-hen7/perseus)) for which routes may be stored in a `struct`, and can only be accessed through the `self` parameter. I've explored global variables and contexts as possible solutions to this problem, but the former ends up requiring generation of core types and the latter becomes quickly infeasible due to the nature of reactive scopes.

Hence, I would propose that the `Route` trait's methods take the `self` parameter so that they can be feasibly implemented on `struct`s as well as `enum`s. In theory, I would think this should be relatively simple, especially because the rest of the user-facing interface should be able to stay exactly the same, though some changes would be needed to the derive macro for `Route`.

**Comment by arctic-hen7** [comment]
Also, this *technically* wouldn't need to move Sycamore to v0.7.0:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

*Quoted from [Semantic Versioning spec](https://semver.org/#spec-item-4) item 4.*

**Comment by arctic-hen7** [comment]
Looking at this in more detail, I'm wondering if such semantics may actually be better implemented with an entirely custom router...

**Comment by arctic-hen7** [comment]
For anyone else encountering this problem, I advise you generate an `enum` with the data you need it to have using a macro if possible. It sounds atrocious, but it actually works quite well if you move as many functions as possible out of the macro!

@lukechu10 if you think this more flexible routing model is worth pursuing in the longer-term for albeit a very niche use-case (framework building), please re-open this issue! Otherwise, the solution above will be sufficient for now I think (for me at least).

**Comment by lukechu10** [comment]
I think the best way to solve this issue is to provide a way to opt-out of the Router attaching a click handler.
This way, Perseus can attach its own handler and not have any conflict at all with Sycamore's. You would still be able to use sycamore's routing infrastructure by manually calling [`navigate`](https://docs.rs/sycamore-router/0.6.0/sycamore_router/fn.navigate.html) instead.

**Comment by arctic-hen7** [comment]
That may be good long-term, but I don't think that's the crux of the issue anymore. As described [here](https://github.com/arctic-hen7/perseus/issues/8), the principle issue appears to be that Sycamore executes Perseus' routing logic properly, but then doesn't continue on to run the closure provided to the `Router` for some reason. I'll start attempting to debug this tomorrow and see if I have any luck, but I think the routing infrastructure seems to be fine as is, it just seems to be doing some kind of overly-aggressive caching.

**Comment by arctic-hen7** [comment]
I'm now trying to remove the magic from Perseus, and I've found myself back at this problem! The issue is that I need to be able to get three Perseus properties (the render config, the templates, and the locales) into the logic the `match_route` function runs. The old system was reacquiring all these by using a macro to generate the `enum`, which is now infeasible with the new design.

It would be really useful if Sycamore could support taking the `&self` parameter to `match_route`, which would allow using `struct` `Route`s that contain custom information.
