### ISSUE TITLE
Documentation about how dependency tracking works

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#252]
Dependency tracking is topological, meaning that dependencies must be accessed before the tracking scope returns.

```rust
create_effect(move || {
    // blah blah...
    
    wasm_bindgen_futures::spawn_local(async move {
        // This scope is not tracked because spawn_local runs on the next microtask tick (in other words, some time later).
    };
    // Everything that is accessed until here is tracked. Once this closure returns, nothing is tracked.
});
```

This means that accessing signals or other dependencies inside something like `wasm_bindgen_futures::spawn_local` will not track the dependencies and might not be what the author intended.

This should be clarified in the documentation about "Reactivity"

**Comment by arctic-hen7** [comment]
I'm happy to do this if you'd like.
