### ISSUE TITLE
Suggest replacing `<..path>` with `<path..>` in `Routes` macro

### ISSUE THREAD

**Issue by jquesada2016** [sycamore-rs/sycamore#256]
The proposed change is minor, but would bring it inline with Rust's spread operator and most other routers that I am familiar with. :)

**Comment by lukechu10** [comment]
What router do you have in mind? Sycamore's router has the same syntax as Rocket which uses `<path..>`.

**Comment by arctic-hen7** [comment]
I too thought about this, but I think it does make more sense for the dots to be on the right, because it indicates a capture of this and anything on the right. That said, an error message for accidentally putting the dots on the left could be useful, as it is an easy mistake to make.

**Comment by jquesada2016** [comment]
I have never used Rocket, so perhaps on the Rust side, the dots are on the right, I was coming from routers on JavaScript land, such as Express and SvelteKit/Sapper, along with Rust's spread operator, since your "spreading" the remaining path segments. I'm perfectly happy with them being on the right. Just thought it might be a bit more consistant.

**Comment by lukechu10** [comment]
> Do you think a specialized warning would be sufficient to let people know that the dots should be on the right with Sycamore?

Shouldn't be too hard. Sounds like a valid feature request to me.

**Comment by lukechu10** [comment]
I no longer think this is really necessary since this is spelled out pretty clearly in the docs already. I'll be closing this now
