### ISSUE TITLE
Need to be able to convert web_sys::Element to Template<G>

### ISSUE THREAD

**Issue by jquesada2016** [sycamore-rs/sycamore#261]
This is important for interfacing with many JS libraries which create arbitrary elements or produce template strings. I was unable to implement `IntoTemplate<G>` due to the blanket implementation, so used instead the `From` trait. It should also be possible in the future to create the template node without needing a wrapper element, though could not find a way from reading through the source. Any tips would be appreciated.

**Comment by arctic-hen7** [comment]
Are you talking about being able to create a `Template` from an existing DOM node? Because that I agree would be extremely useful. Not sure how you'd do it for an `Element` that you hadn't appended to the DOM yet though...

**Comment by jquesada2016** [comment]
Yes! 

If you take a look at my pull request, the way I got around it, was to coerce the element into a string by calling `outer_html()` and `dangerously_add_inner_html` to a `<span>`. It's a workaround for now until a much better solution (and specialization) are implemented...

**Comment by lukechu10** [comment]
> If you take a look at my pull request, the way I got around it, was to coerce the element into a string by calling `outer_html()` and `dangerously_add_inner_html` to a `<span>`. It's a workaround for now until a much better solution (and specialization) are implemented...

This workaround shouldn't be used because this will cause the elements to be recreated. Instead, we should just make a new `DomNode::new` method that creates a `DomNode` from a `&web_sys::Node`. I got some changes in #240 that would conflict with such a change so I can address this in that PR.

In https://github.com/sycamore-rs/sycamore/pull/260, would you please drop commit https://github.com/sycamore-rs/sycamore/commit/9f1dbaede62152a8194249b594537f013f22b05e? You can do so by using `git rebase -i HEAD~1` and then using `git push -f`. Thanks!

**Comment by lukechu10** [comment]
Also if you urgently need a workaround, you can do something like this:
```rust
let my_node: web_sys::Element = ...;

let d = DomNode::element("div");
// Get raw node and append my_node
d.inner_element().append_child(&my_node);

// Get my_node wrapped inside a DomNode
let my_node_template: DomNode = d.first_child().unwrap();
```

**Comment by jquesada2016** [comment]
@lukechu10 rebased and removed commit 9f1dbae

**Comment by jquesada2016** [comment]
> Also if you urgently need a workaround, you can do something like this:
> 
> ```rust
> let my_node: web_sys::Element = ...;
> 
> let d = DomNode::element("div");
> // Get raw node and append my_node
> d.inner_element().append_child(&my_node);
> 
> // Get my_node wrapped inside a DomNode
> let my_node_template: DomNode = d.first_child().unwrap();
> ```

This is a good workaround, but doesn't work for my case at the moment because I've been using `<G: GenericNode>` and trying to return a `Template<DomNode>` doesn't let me use the component anywhere else unless I convert everything to use `DomNode` instead of `G`

**Comment by mc1098** [comment]
#432 which closed this issue adds the `from_web_sys` function which can be used like this:

```rust
fn get_some_raw_node<G: Html>() -> View<G> {
    // get raw web_sys element
    let my_node: web_sys::Element = ...;
    
    // convert a `web_sys::Node` into G
    let node = sycamore::web::from_web_sys(my_node.into());
    // return generic node in a `View`
    View::new_node(node)
}
```

Note: This function does require the trait bound `G: Html` this is to help
limit the scope of `G` as this function does panic if `G` is not a `DomNode`
or a `HydrateNode`.
