### ISSUE TITLE
Need a way to get notified when a node is mounted to the DOM

### ISSUE THREAD

**Issue by jquesada2016** [sycamore-rs/sycamore#272]
### The Problem
Currently, it is not so straightforward on how to get notified when a node is mounted to the DOM. `NodeRef::try_get()` works, but not for code that cannot run until this returns `Some<G>`, One workaround is to call `wasm_bindgen_futures::spawn_local`, which will run on the next micro task, but I can imagine this being unreliable for more complicated rendering scenarios.

### Possible Solution
I propose we implement an `on_mount()` function for `NodeRef` which will recursively call `wasm_bindgen_futures::spawn_local()` until the node is mounted, and only then run the callback function.

This approach has the advantage of being "lazy", meaning it won't block the main thread, in the case the `NodeRef` is never mounted to the DOM. Or perhaps, for correctness, we might try an `on_mount_with_threshold()` or `on_mount_with_timeout()` which would stop trying and panic when the respective recursive threshold calls are reached or the timer expires.

Although a better option would be to use a `MutationObserver`.

**Comment by jquesada2016** [comment]
@lukechu10 Since you mentioned wanting to support other platforms in the future, wouldn't it be wiser to change the `IS_BROWSER` constant to something like `PLATFORM_NAME` or `PLATFORM` with an enum which can include a variant for `custom` for user provided renderers? This does solve the ugly hack, but doesn't help when targeting other runtimes, such as `NativeScript`, `React Native`, etc.

**Comment by lukechu10** [comment]
Added a simple `on_mount` function using `queueMicrotask` under the hood in e0f1d2299f2ae8a229f762803ea1c5068ad09fd2. This should suffice for now but eventually I would like to tie this into the reactive system but that is a problem for another time.
