### ISSUE TITLE
use_context inside a Router can't find context when used after route change

### ISSUE THREAD

**Issue by Zoeycode** [sycamore-rs/sycamore#282]
**Describe the bug**
When `use_context` is called from inside a `Router` after a route change it can't find the context value anymore and panics.

**To Reproduce**
[Use code in reproduction repo](https://github.com/Zoeycode/sycamore-context-testing/blob/main/src/main.rs) and click on link with built site.

**Expected behavior**
`use_context` should return the context.

**Environment**

- Sycamore: master (the repo uses 0.6.3)
- Browser: Edge/Firefox
- OS: Ubuntu 21.04

**Additional context**
As far as I can tell, the context itself isn't being dropped, it's just not being found after the route changes.

When it panics, there's an extra scope being searched in `use_context` which is not created in the `sycamore_reactive::context::create_context_scope` function.

**Comment by Zoeycode** [comment]
As far as I can tell, the problem comes from `create_context_scope` not being run after a route change (because `ContextProvider` has no reactivity of its own?), which means the context is missing when the template set as `ContextProviderProps.children` is re-rendered.

When I move `ContextProvider` into the `create_memo` where the current route is rendered, I get once successful route change before it panics on the next change.

It works if I use `create_context_scope` directly: https://github.com/Zoeycode/sycamore-context-testing/blob/ce0b018045fc0c9f2204df72f53b129b40c9b68e/src/main.rs#L28.

**Comment by haywoood** [comment]
> > I still don't understand why it only fails in the application event that works on a vector of values. In my example, the other action still works without having to do the `create_context_scope` work around.
> 
> 
> 
> It's because in the first handler, you're adding a new value to the list and therefore creating a new `Count` component. When this component is being created, `use_context` is called which then panics. The second handler, instead, just updates the `Signal` which doesn't need to be inside the context's scope (or any scope for that matter).

Ahh, I get it now, thanks for taking the time to explain it @lukechu10!
