### ISSUE TITLE
Add ability to use router to replace current location

### ISSUE THREAD

**Issue by arctic-hen7** [sycamore-rs/sycamore#285]
Right now, to my knowledge, the Sycamore router only supports switching the `window.location`, and it doesn't have anything akin to *replacing* it, which tells the browser not to store the original page in history. For example, let's say the user navigates to `/about`, but they should be redirected to `/en-US/about`. Right now, that would involve manually invoking `window.location.replace()` with `web_sys`, which would reload the entire page and result in the Wasm binary potentially being downloaded twice. Though this is solved by `Cache-Control`, this behavior could be improved by adding the ability to replace the location through the Sycamore router, without needing to resort to fully reloading the page.

I would suggest a new function in addition to `sycamore_router::navigate` called `sycamore_router::navigate_replace` or similar.

Note: see [Perseus #61](https://github.com/arctic-hen7/perseus/issues/61) for an example of this being particularly useful.

**Comment by lukechu10** [comment]
Should be done with https://github.com/sycamore-rs/sycamore/commit/f7e2b24cc5b3d3c144ae345aa7e9ae5d578c4ca0
