### ISSUE TITLE
Documentation rendering on mobile

### ISSUE THREAD

**Issue by ctjhoa** [sycamore-rs/sycamore#302]
**Describe the bug**
The book documentation have a rendering issue.

Background doesn't stretch over the whole width.

**To Reproduce**

1. Go to https://sycamore-rs.netlify.app/docs/getting_started/installation
2. Open dev tools and switch to mobile view (eg. iphone 11 size)
3. Scroll to the right

**Expected behavior**
Full width background

**Screenshots**
![Screenshot_20211117-192717.png](https://user-images.githubusercontent.com/1716173/142261449-e7988221-6cfc-4b14-ba5a-34325071bd60.png)

**Environment**

- Browser: Firefox 94.0

**Comment by martinmcwhorter** [comment]
Is anyone working on this, if not I'll take a stab?

**Comment by lukechu10** [comment]
> Is anyone working on this, if not I'll take a stab?

I think the issue here is really making the website more mobile friendly which would involve collapsing the nav menu into a hamburger menu. I got started a bit on the [`fix-website-css`](https://github.com/sycamore-rs/sycamore/tree/fix-website-css) branch but you're welcome to continue.
