### ISSUE TITLE
Documentation: Iteration example is incorrect (template <-> view)

### ISSUE THREAD

**Issue by AMNRG** [sycamore-rs/sycamore#314]
**Describe the bug**
In the documentation under the section [Iteration](https://sycamore-rs.netlify.app/docs/v0.7/basics/iteration) the property `view` is used in the example, which is however still named `template` in `KeyedProps` and `IndexedProps`.
Maybe we should rename the property for consistency.

**Comment by lukechu10** [comment]
> 

yeah that's a typo in the docs. If you could send a PR, that would be great. Also just change the `next` docs, not the `0.7` docs because that would be updated by next release.
