### ISSUE TITLE
Hydration duplicates interpolated variables

### ISSUE THREAD

**Issue by arctic-hen7** [sycamore-rs/sycamore#319]
**Describe the bug**
When hydrating a view rendered with SSR, any interpolated variables will be duplicated at the element-level.

**To Reproduce**

1. Create a component that interpolates any variable.
2. Prerender that component with SSR using `sycamore::render_to_string()`.
3. Inject that string into the `<body>` of your page with `web_sys`.
4. Hydrate the component with `sycamore::hydrate()`.
5. Observe that the interpolated value is duplicated at the element level (e.g. `Hello World!Hello World!`).

This can also be observed in Perseus from `v0.3.0-beta.22` by creating a page that interpolates a value and then enabling the `hydrate` feature, which enables Sycamore's hydration (and follows a very similar process to that described above).

**Expected behavior**
Interpolated values should be removed, recomputed, and rendered without duplication.

**Screenshots**

![Interpolated value duplication](https://user-images.githubusercontent.com/49536790/146153320-a7d5b334-6fbd-4c42-b601-b04b69a3956e.png)

**Environment**

- Sycamore: v0.7.0
- Browser: Firefox 96.0b4
- OS: Ubuntu

**Additional context**
An MRE for this issue is available [here](https://github.com/arctic-hen7/sycamore-hydration-inteprolation-mre). Use `trunk serve` to run it and observe the issue in a browser.

I assume this is caused by simply not removing the old interpolated values, which I understand would be difficult without knowing exactly what they are. My (perhaps very naive) suggestion would be to identify the smallest number of elements within a component that have interpolated values, and then remove those, recomputing the new values. Alternatively, a more nuanced approach could be taken of isolated interpolated values within strings etc., though this may have a large runtime performance cost (but I'm unfamiliar with this part of the Sycamore codebase, so I honestly have no idea).

**Comment by lukechu10** [comment]
This has been fixed for dynamic nodes that are children of elements, e.g.
```rust
view! {
    div {
        (dynamic_value)
    }
}
```
but doesn't work for dynamic nodes at the top-level, e.g.
```rust
view! {
    (dynamic_value)
}
```

This proved to be a much harder problem to solve and would probably require a lot of refactors so it's nothing I can fix quickly.
