### ISSUE TITLE
Compile-time checked element names

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#327]
Element names should be checked at compile-time for the `view!` macro. This will be implemented by declaring structs for all possible html tags, e.g.
```rust
struct a;
struct button;
struct div;
// etc...
```
This will also allow the opportunity to have nice ide hover support and hopefully completions for html tags.

For custom elements, the syntax will be slightly changed to force the name to be in quotes, e.g.
```rust
view! {
    "my-custom-element" {
        // ...
    }
}
```

**Comment by arctic-hen7** [comment]
Do you think it's worth dynamically generating these for the HTML backend with a build script?
