### ISSUE TITLE
Router reload

### ISSUE THREAD

**Issue by arctic-hen7** [sycamore-rs/sycamore#335]
Right now, Sycamore's router supports navigating to  a new page and also replacing the current entry in the history. Extending on this, it would be useful if the router could reload the current route. At first, I know this seems completely pointless, but, as I've discovered through Perseus' [state freezing](https://github.com/arctic-hen7/perseus/issues/120), it's not! Right now, if you call `navigate(url)` where `url` is the same as the current page, the code in the `Router` callback doesn't run, nor should it.

However, there are cases, particularly for high-level contexts that have been updated, in which reloading a page with new state is extremely useful. This seems to be the offending code:

https://github.com/sycamore-rs/sycamore/blob/86343315e8cd921f8c4618b6dc32fc0191ddceba/packages/sycamore-router/src/router.rs#L112-L113

While I accept that this is a great default, it would be very useful to have a function that bypasses it to enable reloading the current route. Notably, this would probably require a not insignificant refactor of the router, which I'm probably not the best person to attempt due to my unfamiliarity with its intricacies.

**Comment by johan-smits** [comment]
Is there a update on this?
