### ISSUE TITLE
Issue with hydration and cloning signals

### ISSUE THREAD

**Issue by jafioti** [sycamore-rs/sycamore#338]
**Describe the bug**
When I use hydration and clone a Signal, I get an error.

**To Reproduce**
Take the sycamore-rocket-template and swap out the Nav component with:
```rust
#[component(Nav<G>)]
pub fn nav() -> View<G> {
    let title = Signal::new("hello".to_string());
    view! {
        header (class="site-header") {
            nav (class="nav navbar navbar-expand-lg navbar-dark bg-steel fixed-top") {
                (if title.get().is_empty() {
                    view!{p{"Default Title"}}
                } else {
                    let title = title.clone();
                    view!{p{(title.get()) " | Website Title"}}
                })
            }
        }
    }
}
```
When ran, you should see this error:
```
Uncaught (in promise) Error: `unwrap_throw` failed
    at imports.wbg.__wbindgen_throw (index-fdaf8fd498822c9d.js:717:11)
```

**Expected behavior**
I expected it to load in the same as when using render_to but with hydration

**Environment**

- Sycamore: 0.7.1
- Browser: chrome
- OS: Ubuntu 20.04

**Comment by lukechu10** [comment]
I believe this issue is now fixed in `0.8.0-beta.2`. Please reopen if this issue persists for you.
