### ISSUE TITLE
`cloned!` macro doesn't use absolute paths

### ISSUE THREAD

**Issue by arctic-hen7** [sycamore-rs/sycamore#339]
It seems that the `cloned!` macro doesn't use the absolute path to itself, meaning that it can't be used in another macro as `::sycamore::prelude::cloned!`.

https://github.com/sycamore-rs/sycamore/blob/56e8f048061e6ec99f424eef9242cabb15ec15c6/packages/sycamore-reactive/src/lib.rs#L148-L158

I'm happy to try a fix for this, but I'm not sure if you'd want to use an absolute path that goes through `sycamore_reactive` or `sycamore::prelude`... (Perhaps `cloned!` should be redeclared in the Sycamore package?)

**Comment by lukechu10** [comment]
I'm pretty sure we can use `$crate` here since it's a MBE. You're welcome to send a PR if you want and I can cut a new minor release for 0.7 merged. Do note that I'm on the verge of merging #337 which will remove any use for this macro.

**Comment by arctic-hen7** [comment]
I don't need this urgently, I've just worked around by `use`ing it in a new block, and if #337 will make this entirely obsolete (hooray!) then this is fine to be closed I think!
