### ISSUE TITLE
Invalid character in class with builder

### ISSUE THREAD

**Issue by creepinson** [sycamore-rs/sycamore#365]
**Describe the bug**
So I encountered a bug when I was rendering my website using the builder pattern instead of macros as I wanted to have formatting with cargo fmt. However, the same code that works with the macro view! does not seem to work with the builder pattern.

Unfortunately due to the change made in sycamore to change every unwrap to unwrap_throw it does not make it debuggable in the console, so I had to make a fork just to get the full error and not a `caused unwrap_throw` error. [See wasm-bindgen's issue on unwrap throw not showing line numbers](https://github.com/rustwasm/wasm-bindgen/issues/2066).

The weird thing is that I did not use any "invalid characters", the only thing I used is alpha characters and dashes 🤔 

**Expected behavior**
The page to render without errors.

**Screenshots**

**Environment**

- Sycamore: master
- Browser: firefox
- OS: arch linux

**Additional context**

Here is most of the stacktrace:

```
panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(InvalidCharacterError: String contains an invalid character
init/imports.wbg.__wbg_add_c1e566b20be6badb/<@http://localhost:8080/index-96e2b892161547e6.js:563:21
handleError@http://localhost:8080/index-96e2b892161547e6.js:250:18
init/imports.wbg.__wbg_add_c1e566b20be6badb@http://localhost:8080/index-96e2b892161547e6.js:561:62
web_sys::features::gen_DomTokenList::DomTokenList::add_1::h8fe0e96b6861482b@http://localhost:8080/index-96e2b892161547e6_bg.wasm:wasm-function[464]:0x3f1ca
<sycamore::generic_node::dom_node::DomNode as sycamore::generic_node::GenericNode>::add_class::hbdccaff0d63f51a2@http://localhost:8080/index-96e2b892161547e6_bg.wasm:wasm-function[1005]:0x5e7bf
sycamore::builder::agnostic::NodeBuilder<G>::class::h8eb00729ef2ad01c@http://localhost:8080/index-96e2b892161547e6_bg.wasm:wasm-function[1013]:0x5edb7
```

It seems to be something in the add_class method along with the DomTokensList that is causing a problem.

**Comment by creepinson** [comment]
I removed the css classes containing dashes in them and it seems to work. I think for some reason adding a `-` in the css class causes it to break...

**Comment by lukechu10** [comment]
That's quite weird. I'll try to do some further investigation soon.
