### ISSUE TITLE
wasm bindgen example

### ISSUE THREAD

**Issue by g00nix** [sycamore-rs/sycamore#394]
A wasm bindgen example would be good for all cases where JavaScript is still required. One use case would be to interact with various browser extensions, like Metamask or Phantom App. This would look like this on the rust side:
```rust
#[wasm_bindgen(module = "/js/solana.js")]
extern "C" {
    #[wasm_bindgen(catch)]
    async fn connect_to_wallet() -> Result<JsValue, JsValue>;
}
```
And the javascript part in file `js/solana.js`:
```javascript
export async function connect_to_wallet() {
  try {
    const resp = await window.solana.connect();
    return resp.publicKey.toString();
  } catch (err) {
    return err;
  }
}
```

After this, the rust future can be called with `connect_to_wallet().await` and the `JsValue` has to be handled via sycamore.

**Comment by lukechu10** [comment]
> I would like to do that.

Awesome! Also I think it would be better for the example if it did not pull in an extra JS library. Instead, it would probably be best if the JS were completely self-contained. That way, we keep the example nice and simple. Maybe just implement some kind of math function, or some DOM operation in JS that can be called in Rust.

If you have any questions, don't hesitate to ask me.
