### ISSUE TITLE
Implement `Debug` for public `struct`s

### ISSUE THREAD

**Issue by arctic-hen7** [sycamore-rs/sycamore#412]
In my experience, it's generally a good idea to do this, even if the implementation just says the name of the `struct`. Also, I need to put `Scope`s into `struct`s that implement `Debug` for Perseus, so it would be nice if `BoundedScope` implemented it.

I'm happy to work on a PR for this that just implements fairly naive `Debug`s (if it can't be derived, just say the name of the `struct` and move on) on all public `struct`s, but I thought I should open this first to check there aren't any objections.

**Comment by lukechu10** [comment]
That sounds like a good idea. For the case of `BoundedScope`, I think just printing `BoundedScope` should be fine because some fields are implementation details and not very relevant.

**Comment by arctic-hen7** [comment]
Great, I'll get to work on this when I get out of the lifetime tangle I'm in at the moment!

**Comment by lukechu10** [comment]
Hey @arctic-hen7, was wondering if you're still planning to implement this. If not, I'll let someone else (maybe myself) takeover if that's ok. If you do what to do this, don't feel pressured; there's still quite a lot of work left before 0.8.

**Comment by arctic-hen7** [comment]
Thank you for the reminder! I'll try to get this done some time in the next week, but I really don't mind if you want to do it before then.
