### ISSUE TITLE
E0061 when trying to call a component without props in Builder API

### ISSUE THREAD

**Issue by Dragonink** [sycamore-rs/sycamore#415]
**Describe the bug**
I get the Rust error `this function takes 2 arguments but 1 argument was supplied` when trying to call a component without props with the Builder API.

**To Reproduce**
```rust
#[component]
fn App<G: Html>(cx: Scope) -> View<G> {
	// ...
}
#[wasm_bindgen(start)]
pub fn start() {
	sycamore::render(|cx| App(cx)); // ERROR
	sycamore::render(|cx| App(cx, ())); // WORKS
}
```

**Expected behavior**
I expect to be able to call the component like a normal function, as I was able to in the previous version.

**Environment**
- Sycamore: `0.8.0-beta.5`

**Comment by mc1098** [comment]
This part of the `#[component]` macro code https://github.com/sycamore-rs/sycamore/blob/c9e7623a366c92ffcfa7bc362cddee395500e44c/packages/sycamore-macro/src/component/mod.rs#L85-L88
was added in 881cddb.
That commit made empty props implicit for the component definition but made it explicit when calling the component - I'm not sure if there was a reason behind making it explicit that I'm not aware of but @lukechu10 would know :)

If this can be changed then from my quick scan of the macro code I think we'd just need to remove those few lines I linked above 🤔.
