### ISSUE TITLE
Inline Props

### ISSUE THREAD

**Issue by jafioti** [sycamore-rs/sycamore#430]
It would be a really nice improvement for Components if we could use an inline_prop style macro to allow for something like this:
```rust
#[component]
fn Component<'a, G: Html>(cx: Scope<'a>, title: String, name: &'a Signal<String>) -> View<G> {
    view!{cx,
        p {(title)}
        p {(name.get())}
    }
}
```
and then call it like so:
```rust
Component {
    title: "Howdy".to_string(),
    name: create_signal(cx, "Hello".to_string()),
}
```
Dioxus has a similar feature: https://dioxuslabs.com/guide/components/propsmacro.html
I think if this was built into the `component` macro, such that no additional macro would need to be used, that would be the cleanest implementation.

**Comment by lukechu10** [comment]
> I think if this was built into the `component` macro, such that no additional macro would need to be used, that would be the cleanest implementation.

The problem with this is the case of only a single argument. Should that be the props type or just a field in the props? I think to remove this ambiguity, the best would be to use `#[component(inline_props)]`
