### ISSUE TITLE
Should 'contenteditable' remain as AttributeType::Bool?

### ISSUE THREAD

**Issue by gobuki** [sycamore-rs/sycamore#439]
**Describe the bug**
When I set `span(contenteditable=false) {...}`, the `contenteditable` attribute in the resulting HTML is absent instead of `"false"`. 

**To Reproduce**
See above, but I can make an example project if necessary. 

**Expected behavior**
For `contenteditable`, one should be able to set the value to a string that is "true", "false", or an empty string (equivalent to "true"). There are times when one requires explicitly setting `contenteditable` to "false" for an element, such as when the parent element is editable but the child element should not inherit it. (For example, given an editable `p`, and you require a non-editable child `span` that should be deleted as a whole when you hit backspace at the beginning on its next sibling, which is editable).

**Environment**

- Sycamore: 0.7
- Browser: Firefox
- OS: macOS

**Additional context**
On Sycamore 0.7.* because I am using the corresponding version of Perseus, but my reading of [source code on master](https://github.com/sycamore-rs/sycamore/blob/95a7e14ab52ad12329fc27728e8c428650b931df/packages/sycamore-macro/src/view/codegen.rs#L311) suggests this is still how 'contenteditable' is treated. 

(This is secondary, but I'd also appreciate it if anyone might share existing workarounds for attributes so I can use `contenteditable="false"` on 0.7.* without forking)

Thanks so much!

**Comment by mc1098** [comment]
> Should 'contenteditable' remain as AttributeType::Bool?

No. As far as I can tell it is an enumerated attribute not a boolean attribute. In the [WHATWG list of attributes](https://html.spec.whatwg.org/multipage/indices.html#attributes-3) it explicitly states whether the attribute is a boolean attribute and `contenteditable` is not stated as such.

As for workarounds on 7.*... you could look into using the builder API for this part or you could create a `GenericNode` instance using the generic `G` and add the attributes etc manually. I'm not sure if there is a better way then this 🤔 but I hope it helps.

A possible not breaking backport fix could be to parse string literals as attributes not to be checked against the boolean attributes list but depends on what @lukechu10 thinks about that or whether he knows a better work around.
So would look like this: `span("contenteditable"="false")`.

<details>
<summary>List of Boolean Attributes (for later PR to check boolean attributes)</summary>
<br>
While I had the information up thought I'd note it down here, but hidden away to not be too distracting :)

List of boolean attributes found in the <a href="https://html.spec.whatwg.org/multipage/indices.html#attributes-3">table of attributes on the WHATWG standard</a>

1. `allowfullscreen`
2. `async`
3. `autofocus`
4. `autoplay`
5. `checked`
6. `controls`
7. `default`
8. `defer`
9. `disabled`
10. `formnovalidate`
11. `hidden`
12. `inert`
13. `ismap`
14. `itemscope`
15. `loop`
16. `multiple`
17. `muted`
18. `nomodule`
19. `novalidate`
20. `open`
21. `playsinline`
22. `readonly`
23. `required`
24. `reversed`
25. `selected`

There are actually quite a few attributes in Sycamore's list (added for convenience) that are not in this one:
https://github.com/sycamore-rs/sycamore/blob/1c06c9b41bfd6e657bfc7f5d12d4c40b8d006a20/packages/sycamore-macro/src/view/ir.rs#L87-L130

_List from master, we can't change 7.* as it would be a breaking change_
</details>

**Comment by lukechu10** [comment]
A super simple backport would just be to remove `contenteditable` from the list of boolean attributes (which is the correct behavior anyways). However, that would mean I'd need to create a new branch for `0.7` because the git repo history has been completely linear for the time being. If you don't mind using the builder API temporarily, I think that would be the best solution for now.

**Comment by mc1098** [comment]
With #440 merged this fixes this issue for v0.8.0-beta.7 and above :) I'm not sure if that closes this issue or whether it should remain open until the v0.8.0 release?

**Comment by gobuki** [comment]
I appreciate the fix!
