### ISSUE TITLE
Undefined Behavior when using `Drop` with `create_ref`

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#494]
**Describe the bug**
Undefined behavior can occur in completely safe code when allocating a `Drop` type with `create_ref`.

**To Reproduce**
```rust
use std::cell::Cell;
use sycamore::prelude::*;

struct Foo<'a> {
    r: Cell<Option<&'a Foo<'a>>>,
    value: String,
}

impl<'a> Drop for Foo<'a> {
    fn drop(&mut self) {
        if let Some(r) = self.r.get() {
            dbg!(&r.value);
        }
    }
}

fn main() {
    create_scope_immediate(|cx| {
        let a = create_ref(
            cx,
            Foo {
                r: Cell::new(None),
                value: "hello".to_string(),
            },
        );
        let b = create_ref(
            cx,
            Foo {
                r: Cell::new(Some(a)),
                value: "world".to_string(),
            },
        );
        a.r.set(Some(b));
    });
}

```

**Expected behavior**
Undefined behavior should never happen in safe code.

**Environment**

- Sycamore: 0.8.2

**Additional context**
Luckily, there is a solution to this. `typed-arena` offers a similar API as `create_ref` but does not suffer from this problem: https://github.com/SimonSapin/rust-typed-arena/issues/24

This is also related to "drop checking" in Rust which is described in detail over here: https://doc.rust-lang.org/nomicon/dropck.html
Somehow, `create_ref` is not triggering dropck.

Additional resources about dropck: https://exyr.org/2018/rust-arenas-vs-dropck/

I suspect this is because the compiler doesn't know the type that is being dropped when `ScopeArena` is dropped.

**Comment by loichyan** [comment]
As a workaround, it should be safe to restrict `create_ref<T>(...)` accepts `<T: 'static>`, and expose original function as an unsafe one.

**Comment by loichyan** [comment]
> We can avoid the 'static bound while making everything safe with the aforenoted dropck feature.

It seems impossible to perform dropck on the type erased `Arena` 🤔. I found two crates [dynamic-arena](https://crates.io/crates/dynamic-arena) and [erased-type-arena](https://crates.io/crates/erased-type-arena), the former requires the allocated type is `Copy`, and the latter wraps the underlying value with a smart pointer which checks for dangling reference at runtime. Additionally, another similar arena (zakarumych/scoped-arena#1) takes the approach I mentioned above.

IMO, we can introduce a smart pointer for general types and expose safe APIs for `Copy` and `'static` types.

**Comment by loichyan** [comment]
Hmm, I think I may have figured out why dropck doesn't work in `Scope<'a>` 🤔:

```rs
struct Container<'a> {
    _phantom: std::marker::PhantomData<&'a mut &'a mut ()>,
}

impl<'a> Container<'a> {
    fn store<T: 'a>(&'a self, t: T) -> &'a T {
        todo!()
    }
}

impl Drop for Container<'_> {
    fn drop(&mut self) {}
}

// The `Scope<'a> is a wrapper of `&'a RawScope<'a>`, so it's the same case as below.
// In this function we cannot determinate which is 'a being bounded to so it could
// be any lifetime.
fn dropck_doesnt_work<'a>(container: &'a Container<'a>) {
    let val = container.store(0);
    container.store(val);
}

fn dropck_works<'a>(container: Container<'a>) {
    // Here we can infer that 'a is the lifetime of given `container` which is
    // owned by this fuction. However, the dropck requires 'a outlive
    // `Container` due to the implementation of `Drop` which is definitely not satisfied.
    let val = container.store(0);
    container.store(val);
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=338ddcdc38abaf47b5d168dfb5dd81df)
