### ISSUE TITLE
Support `impl Trait` syntax with `inline_props`

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#507]
Right now, `inline_props` does not support the `impl Trait` syntax which is often useful to prevent adding tons of generics to a function.

We would like the following syntax to work out of the box:
```rust
#[component(inline_props]
fn MyComponent<G: Html>(cx: Scope, foo: impl MyTrait) -> View<G> {
    ...
} 
```

The difficulty with this is that we cannot directly translate `impl MyTrait` into a struct field because this syntax is only supported for functions. We therefore need to manually transform the `impl MyTrait` into an explicit generic parameter in the generated struct.

**Comment by davidon-top** [comment]
I've done something similar in [rstml-component](https://github.com/YoloDev/rstml-component/pull/15), i will make a pr once i have a starting point.
