### ISSUE TITLE
DOM assets are reloaded after hydration

### ISSUE THREAD

**Issue by danielnehrig** [sycamore-rs/sycamore#512]
**Describe the bug**
after hydration takes place assets are reloaded.
for instance images are loaded twice due to this resulting in longer load times.

**To Reproduce**

1. hydrate with a image in the dom

**Expected behavior**
We do not do another redundant network call

**Screenshots**
<img width="1239" alt="bug" src="https://user-images.githubusercontent.com/4050749/196514757-32b2b387-7c92-4663-acf6-7d93cc93de9b.png">

**Environment**

- Sycamore: 0.8.2
- Browser: chrome
- OS: linux

**Comment by danielnehrig** [comment]
workaround is to set a cache control header so the images are not fetched again but reused.

**Comment by arctic-hen7** [comment]
No clue really, but could you hypothetically fix this by having all your assets in a non-Sycamore place and then using the shadow DOM to tunnel them through? A component for this shouldn't be impossible as an interim workaround...
