### ISSUE TITLE
Consolidate `HydrateNode` into `DomNode`

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#542]
The current split is a bit confusing and not very useful. It would be better to merge `HydrateNode` back into `DomNode`. The hydration-specific functionality can still be feature-gated to not pay the performance penalty when it is not needed.

**Comment by arctic-hen7** [comment]
This would be extremely beneficial for Perseus, as it would allow more idiomatic distinctions between rendering and hydration (sometimes in Perseus, even when we're asked to hydrate, we actually need to fully render, e.g. if we have more info about an error than the server did). More broadly, I think this will help a lot of future systems doing any kind of SSR error handling!
