### ISSUE TITLE
API docs correction for Functions hydrate_to: "use hydrate_to" should read and link as "use hydrate"

### ISSUE THREAD

**Issue by StarSapien** [sycamore-rs/sycamore#578]
In https://docs.rs/sycamore/latest/sycamore/ under Functions hydrate_to it currently reads and links as: 
"Render a [View](https://docs.rs/sycamore/latest/sycamore/view/struct.View.html) under a parent node by reusing existing nodes (client side hydration). For rendering under the \<body> tag, use **hydrate_to** (https://docs.rs/sycamore/latest/sycamore/fn.hydrate_to.html) instead."

It should read and link as:
"Render a [View](https://docs.rs/sycamore/latest/sycamore/view/struct.View.html) under a parent node by reusing existing nodes (client side hydration). For rendering under the \<body> tag, use **hydrate** (https://docs.rs/sycamore/latest/sycamore/fn.hydrate.html) instead."

**Comment by mc1098** [comment]
This can be changed here, if you want to submit a PR 🙂:
https://github.com/sycamore-rs/sycamore/blob/0512e4a6e7e60b6f2611c6984585c90126b69018/packages/sycamore-web/src/hydrate_node.rs#L356-L365

Change the "[`hydrate_to`]" to "[`hydrate`]" on line 357.

**Comment by StarSapien** [comment]
Ok I think that worked. I assume docs.rs has their own update interval now?

Thank you for Sycamore, I think it's a great project.

**Comment by StarSapien** [comment]
Thank you for Sycamore, I think it's a great project.
