### ISSUE TITLE
Failed to iterate over a vector from the Keyed iteration. 

### ISSUE THREAD

**Issue by afidegnum** [sycamore-rs/sycamore#581]
**Describe the bug**
from the iteration, I'm not able to apply the `has_child()` which iterates the supplied vector and determine the `bool` status of the current element.
This is a hierarchical node where I need to display if a node contains a child and when iterated, everything returned false which is a bug. 

**To Reproduce**
This works on the [following repo](https://github.com/afidegnum/SycaComps/blob/main/treetest/src/main.rs#L70) when picked the element by index.

The [error is happening at ](https://github.com/afidegnum/SycaComps/blob/main/sycatree/src/main.rs#L108)
![image](https://user-images.githubusercontent.com/374206/220601361-16a75dcb-6454-48ea-8188-2197ffef371e.png)

**Expected behavior**
I was expected to see  `Node1 True`, `Node2 True`, `Node3 True` and the rest being false.

**Comment by afidegnum** [comment]
bump!

**Comment by lukechu10** [comment]
Closing due to stale. Please re-open if you still experience this issue.
