### ISSUE TITLE
run instructions for Hello World example fail with sycamore 0.8

### ISSUE THREAD

**Issue by godmar** [sycamore-rs/sycamore#584]
**Describe the bug**

Following the instructions on the [v0.8](https://sycamore-rs.netlify.app/docs/v0.8/getting_started/installation) website for the "Hello World" application results in a non-working application when `Cargo.toml` contains `0.8` as sycamore version.

**To Reproduce**
Follow the steps listed [here](https://sycamore-rs.netlify.app/docs/v0.8/getting_started/installation) and run
```
trunk serve
```
which shows:
```
$ trunk serve
2023-03-10T14:18:52.605407Z  INFO 📦 starting build
2023-03-10T14:18:52.606447Z  INFO spawning asset pipelines
2023-03-10T14:18:52.704931Z  INFO building sycamore
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
2023-03-10T14:18:52.765983Z  INFO fetching cargo artifacts
2023-03-10T14:18:52.825176Z  INFO processing WASM for sycamore
2023-03-10T14:18:52.826829Z  INFO calling wasm-bindgen for sycamore
2023-03-10T14:18:52.835853Z  INFO copying generated wasm-bindgen artifacts
2023-03-10T14:18:52.836719Z  INFO applying new distribution
2023-03-10T14:18:52.837503Z  INFO ✅ success
2023-03-10T14:18:52.837676Z  INFO 📡 serving static assets at -> /
2023-03-10T14:18:52.837712Z  INFO 📡 server listening at http://127.0.0.1:8080
```

**Expected behavior**
It should show "Hello World". Instead, it serves the development server webpage, creates a websocket, but no traffic is ever observed over the websocket and the DOM doesn't update.

**Environment**

- Sycamore: 0.8.0
- Browser: Firefox or Chrome
- OS: Linux Ubuntu 22.04

**Additional context**

Looking up the latest commit hash and changing `Cargo.toml` to read:
```
# sycamore = "0.8"
sycamore = { git = "https://github.com/sycamore-rs/sycamore", rev = "4eb5852d67cf45665d6bf957aaa534f33c961129" }
```
results in `Hello World` being displayed as advertised.

```
$ trunk --version
trunk 0.16.0
$ rustc --version
rustc 1.68.0 (2c8cc3432 2023-03-06)
$ cargo --version
cargo 1.68.0 (115f34552 2023-02-26)
```
```

**Comment by lukechu10** [comment]
Can you please provide more information? As far as I know, sycamore v0.8 should still work perfectly fine. For example, what do you see in the browser's network panel?

**Comment by godmar** [comment]
Sure.  First, here is what I see for the working snapshot.

![image](https://user-images.githubusercontent.com/486389/224449571-44a2bd72-4ff0-4a55-ac8e-87c5c3a530e8.png)

I think the app should be in the `.wasm` (there's also no traffic over the websocket, which I'm guessing is for hot module reload?).

The 0.8 version which does not work shows:
![image](https://user-images.githubusercontent.com/486389/224450186-5132c814-f052-45e6-8cc7-9494fe124b35.png)

The attached zip file contains the `.wasm` file it serves if that's useful.
[sycamore.zip](https://github.com/sycamore-rs/sycamore/files/10946917/sycamore.zip)

**Comment by lukechu10** [comment]
It doesn't seem like you've actually compiled sycamore, judging from the size of the wasm binary. Are you sure you are compiling the right project? What if you do something that is not related to sycamore, does that work?

**Comment by godmar** [comment]
I ran `trunk serve` and it showed that it was building it. That said, I can't reproduce this anymore, even with `cargo clean; cargo cache -a`. Maybe it didn't pick up when I changed `src/main.rs`?  But that would be inconsistent with getting it fail after switching `Cargo.toml` back to `"0.8"`.  In any event, may not be worth tracking down this glitch.
