### ISSUE TITLE
view! compile error when passing empty Children through component

### ISSUE THREAD

**Issue by zdenek-crha** [sycamore-rs/sycamore#588]
**Describe the bug**

When component prop struct contains *only* `Children` struct and `view!` macro is used to render it *without* child node(s), then compilation fails with `an argument of type AppProps<'_, _> is missing`.

**To Reproduce**

```
use sycamore::prelude::*;

#[derive(Prop)]
pub struct AppProps<'cx, G: Html> {
    children: Children<'cx, G>,
}

#[component]
pub fn App<'cx, G: Html>(cx: Scope<'cx>, props: AppProps<'cx, G>) -> View<G> {
    let children = props.children.call(cx);
    view! { cx, (children) }
}

pub fn main() {
    sycamore::render(|cx| view! { cx,
        App { }
    });
}
```

**Expected behavior**

Code compiles without issue and `AppProps` contains `Children` struct instance that has no child nodes.

**Environment**

- Sycamore: 0.8.2

**Additional context**

This seems to be an edge-case in `view!` macro building the `AppProps` struct from component attributes and children. It manifests *only* in the case described above. Any of the following changes will make it compile:

- add attribute to `App` component when rendering (requires adding field to `AppProps` struct)
- add child node to `App` component rendering (even empty string `""` will help)

**Comment by lukechu10** [comment]
This issue was actually solved way back with #548, I just didn't realize it 😅
