### ISSUE TITLE
`on_rendered` hook

### ISSUE THREAD

**Issue by athanclark** [sycamore-rs/sycamore#592]
Similarly to the `on_cleanup` hook, it would be nice to invoke a function as soon as DOM nodes have been created, rather than do something crude with timeouts - this would make it much easier to bind with front-end libraries like MathJax, which are easiest to use by parsing the existing DOM.

**Comment by lukechu10** [comment]
This already exists! Check out [`on_mount`](https://docs.rs/sycamore/0.8.2/sycamore/web/fn.on_mount.html).
