### ISSUE TITLE
Builder pattern `button().on(ev::click...)` fails: undeclared crate or module.

### ISSUE THREAD

**Issue by dessalines** [sycamore-rs/sycamore#605]
**Describe the bug**

When you do:

`button().on(ev::click,...)`

It fails with:

`Use of undeclared crate or module ev`

I've tried including the `web` feature, still no luck.

**To Reproduce**

See above

**Expected behavior**

ev should be included in prelude?

- Sycamore: 0.8.1

**Comment by dessalines** [comment]
Okay I realized after checking the API that it should just be the string "click".

That means the docs at the bottom of this page should be updated: https://sycamore-rs.netlify.app/docs/basics/view

**Comment by lukechu10** [comment]
The docs that you linked to is for the development version of sycamore. There is also a 0.8 version which uses a string instead.

**Comment by dessalines** [comment]
Oops, my bad.
