### ISSUE TITLE
`component(|| MyComponent` seems to serve no purpose.

### ISSUE THREAD

**Issue by dessalines** [sycamore-rs/sycamore#606]
**Describe the bug**

I've tested out the reactivity of doing:

`.c(MyComponent(...)`

vs.

`.c(component(|| MyComponent(...))`

Both compile and function the same.

And the latter appears to serve no purpose. Components already return `View<G>`, so what purpose does it serve?

- Sycamore: 0.8.1

**Comment by gbj** [comment]
What does `component()` do?

Calls your function inside `component_scope`
https://github.com/sycamore-rs/sycamore/blob/fedc881f2490da4c7abab7d9b1961d4e064a12c0/packages/sycamore/src/builder.rs#L882-L887

What does `component_scope()` do?
https://github.com/sycamore-rs/sycamore/blob/fedc881f2490da4c7abab7d9b1961d4e064a12c0/packages/sycamore-core/src/component.rs#L19-L28

Calls your component within `untrack()`.

Why does it do this? This prevents a signal read inside your component body from subscribing itself to an effect outside your component body, which would cause the entire component to rerender every time that signal changed.

This is very common in fine-grained reactive libraries. Much like not wearing a seat belt, omitting `component(|| ...)` won't cause you any issues until it does, and then you'll wish you'd just always done it.
