### ISSUE TITLE
Builder version `input().bind_value(...)` has requirements that the `view! ` macro doesn't

### ISSUE THREAD

**Issue by dessalines** [sycamore-rs/sycamore#607]
**Describe the bug**

When using the builder pattern `input().bind_value(...`, perseus gives me an error

`thread 'main' panicked at 'function not implemented on non-wasm32 targets'`

As a workaround , I'm doing:

`.c(view! { cx, input(class = "input", bind:value = ...)})`

This implies the builder pattern version has dependencies that the view! macro version doesn't.

**Environment**

- Sycamore: 0.8.1

Context: https://github.com/framesurge/perseus/issues/279

**Comment by lukechu10** [comment]
I'm afraid I can't reproduce this. Looking at the code, `set_property` for `SsrNode` is a no-op so there shouldn't be any panic. Can you provide the source location where the panic occurred?

**Comment by dessalines** [comment]
Sure, here's a backtrace: http://sprunge.us/nQ9s5Z

**Comment by lukechu10** [comment]
Thanks!
