### ISSUE TITLE
Documentation recommends deprecated `weealloc`

### ISSUE THREAD

**Issue by vi** [sycamore-rs/sycamore#614]
For minimizing wasm size, Sycamore docs [recommend](https://github.com/sycamore-rs/sycamore/blob/abce04fe341740c3c9245622208fb5a7ea792498/docs/next/advanced/optimize_wasm_size.md?plain=1#L15) using Weealloc. But this repository is [no longer recommended to use](https://github.com/rustwasm/wee_alloc/issues/109) and links to it should be phased out.

Other mini-alloc such as `lolalloc` should be recommended instead.

Precedent: https://github.com/rustwasm/wasm-pack/issues/1258

**Comment by lukechu10** [comment]
I think for now the best would just be to remove the suggestion for replacing the allocator all-together since `lol-alloc` is a much smaller project than `wee-alloc`. We can maybe re-introduce this when/if there is a better allocator available.
