### ISSUE TITLE
view! failing when attribute name ends in `-ref`

### ISSUE THREAD

**Issue by smessmer** [sycamore-rs/sycamore#620]
**Describe the bug**
To integrate with `Tailwind Elements`, I need to create `div` (and other) elements with a `data-te-dropdown-ref` tag. I tried:
```
view! { cx,
  div(class="relative", data-te-dropdown-ref=true) {}
}
```

but this fails the `perseus serve` with:
```
error: expected identifier
 --> src/components/twelements/dropdown.rs:7:48
  |
7 |         div(class="relative", data-te-dropdown-ref=true) {}
  |                                                ^^^
```

**Environment**

- Sycamore: 0.8.1 with Perseus 0.4.2
- OS: Linux

**Comment by lukechu10** [comment]
This should be a pretty easy fix in the `view!` macro. Right now, we just parse attributes as a sequence of identifiers but `ref` is a keyword. Instead, we just need to use the `Ident::parse_any` function from `syn` instead of just `Ident::parse`.
