### ISSUE TITLE
Abstract over reactiveness

### ISSUE THREAD

**Issue by smessmer** [sycamore-rs/sycamore#623]
Is there a way / or can there be a way added to make Props members abstract over whether they're reactive or not?

Say we have a `Switch` component. There's two ways we could write its props:
```rust
// Reactive
#[derive(Prop)]
pub struct SwitchProps<'cx> {
    checked: &'cx Signal<bool>,
    disabled: &'cx ReadSignal<bool>,
    color: &'cx ReadSignal<String>,
    // ...
}

// Not Reactive
#[derive(Prop)]
pub struct SwitchProps<'cx> {
    checked: bool,
    #[builder(default)]
    disabled: bool,
    color: String,
    // ...
}
```

Likely, the call site wants some of these props to be reactive (e.g. `checked`) and others not (e.g. `color`). But maybe other call sites do actually want the `color` to be reactive as well.

Just making all props reactive, just in case a call site needs it, is likely suboptimal because wrapping everything in a `Signal` causes additional CPU and heap storage overhead. Also, using it from, say, a `view!` macro isn't very convenient because you have to call `create_signal` for every attribute, even if you don't need it to be reactive:
```rust
// We need this
view! {cx,
  Switch(
    disabled=create_signal(cx, false),
    color=create_signal(cx, "red"),
  )
}

// Instead of just this
view! {cx,
  Switch(
    color="red",
  )
}
```
(note also how the non-signal version can just omit `disabled` because it has a default set, but the reactive version can't).

With all these problems, I started wondering - is there a way to write a component to be abstract over whether it's properties are reactive so that the call site can choose? Either by
- specifying a special type (e.g. `MaybeSignal<String>`) in the prop
- or by having some `constant_signal` function that creates a signal for an immutable value **without the overhead of having an actually reactive signal**, and that gets automatically applied by `view!` so users can use `view!` **as if the prop was non-reactive**?

**Comment by lukechu10** [comment]
Yup we definitely need something like this. I'll be working on this for the next release.
