### ISSUE TITLE
Panic updating signal in 0.9.0-beta.2

### ISSUE THREAD

**Issue by Jan-V2** [sycamore-rs/sycamore#645]
**Describe the bug**
Updating a signal in the following component causes a panic, which it didn't before updating.

The panic is:  panicked at 'invalid SlotMap key used', ../sycamore-reactive-0.9.0-beta.2/src/root.rs:323:9

```
#[component(inline_props)]
pub fn ArmyPlacementStart<G: Html>(
    ui_state: Signal<UiState>,
    ui_info: Signal<StartArmyPlacementInfo>,
) -> View<G> {
    let cause_crash = true;

    gloo::console::log!("running place start");
    create_effect(move || {
        let mut _ui_info = ui_info.get();
        if _ui_info.armies_per_player[_ui_info.current_player as usize] == 0 {
            if _ui_info.current_player + 1 < _ui_info.num_players {
                ui_info.set(ui_info.get().update(|s| {
                    s.current_player = s.current_player + 1;
                    s.is_done = false;
                    log!("updating current player");
                }));
            } else {
                log!("updating ui state");
                if cause_crash{
                    ui_state.set(UiState::GAME_END);  // <- this lines causes a panic
                }
            }
        }
    });

    view! {
            h1{"Player " (ui_info.get().current_player + 1 )}
            div{"You still have " (ui_info.get().armies_per_player[ui_info.get().current_player as usize])  " armies to place"}
    }
}
```

**To Reproduce**
the bug can be reproduced as follows:
1. clone the repo at https://github.com/johnvanderholt/wasm_risk/tree/3b9ad6a8e9e20546b28173ef234cae8df4473e3a and run the code using sh run.sh
2. select two players in the setup menu until you get to the army placement menu
3. place armies, until the last player runs out, and the panic happens.

**Expected behavior**
The signal gets updated, and different view is loaded.

**Environment**
- Sycamore:  {version = "0.8.2", features = ["wasm-bindgen", "web", "web-sys", "sycamore-web"]}
- Browser:Firefox
- OS: Lubuntu (flavor of ubuntu)

**Additional context**
The signal gets updated elsewhere, and the view gets changed without issue.
This happens at ui/player_setup.rs:154
This also didn't happen before updating to the beta.
It also doesn't matter which view i switch to, i always get the same panic.

**Comment by lukechu10** [comment]
I'm afraid there's not much I can do without a MRE so I'm going to close this for now. If you encounter any more problems, please feel free to reopen this issue or create a new issue.
