### ISSUE TITLE
Book (website) routing not properly updating

### ISSUE THREAD

**Issue by lukechu10** [sycamore-rs/sycamore#648]
**Describe the bug**
When navigating to a new page in the Book, there is sometimes what seems to be a race-condition which causes the following visual bug to happen:
![image](https://github.com/sycamore-rs/sycamore/assets/37006668/84b5e527-f6c5-46d4-aa46-7273551b9a6b)
[Relevant Discord discussion](https://discord.com/channels/820400041332179004/820400041332179009/1173039854007877682)

**To Reproduce**

1. Go to https://sycamore-rs.netlify.app/docs/getting_started/hello_world
2. Click on another page from the sidebar, e.g. "Hello World!"
3. (Maybe) observe the visual bug.

**Environment**

- Sycamore: 0.9.0-beta.2, current master (16acf8e)
- Browser: Edge 119

**Comment by Saplyn** [comment]
It seems that the book works normal now. *Edge Version 121.0.2277.4 (Official build) stable app, beta channel (64-bit)*

**Comment by lukechu10** [comment]
The annoying part is that I'm only able to reproduce this sometimes and always when I think I've solved the issue. So I'll leave this open for now until I'm more certain that it's fixed.

**Comment by steven89** [comment]
I can consistently reproduce on `Chromium: 122.0.6261.69`:
1. navigate to [https://sycamore-rs.netlify.app/](https://sycamore-rs.netlify.app/) (navigating directly to the home page or reloading on the homepage if I come from another page)
2. press either
  - "Get Started" button in the middle of the page
  - "Book" menu at the top
3. Navigating within the docs with the links now creates rendering issue, as well as scrolling the left-side menu
4. reloading the page while in the docs fixes the rendering

Left side menu scrolling issue:
<img width="193" alt="Screenshot 2024-02-28 at 10 02 55 AM" src="https://github.com/sycamore-rs/sycamore/assets/609271/b4fca317-a9b8-47e7-9a6e-85afb5bffb32">

**Comment by steven89** [comment]
Also once in the docs (after a reload) clicking on a `latest version` link ("For up-to-date documentation, see the [latest version](https://sycamore-rs.netlify.app/docs/v0.8/getting_started/installation) (v0.8).") restarts the rendering issue, again reloading the page afterwards fixes it.

**Comment by Hmikihiro** [comment]
I can reproduce on Firefox 123.0 for MacOS.

When I clicked 'Get Started', the `<div class="flex w-full">` tag was created twice.
The website updates only the second `<div class="flex w-full">`tag and leaves the others unchanged after I clicked a link on the navigation.
In addition to, right-side menu for 'Getting Started' was overwritten by one for 'Basics'


https://github.com/sycamore-rs/sycamore/assets/29543842/88296866-c9f8-4847-8a38-6e930eb5729c

**Comment by lukechu10** [comment]
> I can reproduce on Firefox 123.0 for MacOS.
> 
> When I clicked 'Get Started', the `<div class="flex w-full">` tag was created twice. The website updates only the second `<div class="flex w-full">`tag and leaves the others unchanged after I clicked a link on the navigation. In addition to, right-side menu for 'Getting Started' was overwritten by one fo

Ah thanks for digging into this. Apologies I've just been really busy with other things lately so haven't even gotten a chance to look at this. But this does make it clearer what went wrong!

**Comment by lukechu10** [comment]
Ok another test case, starting on one of the doc pages and clicking on the logo in the top-left doesn't seem to work either.

**Comment by Hmikihiro** [comment]
Clicking on the "News" also works like clicking on the logo.


https://github.com/sycamore-rs/sycamore/assets/29543842/7f004313-798d-4491-803a-bea0eda424e3

**Comment by lukechu10** [comment]
Since we now have a new docsite, this issue is no longer relevant.
