### ISSUE TITLE
Shared data update failed when nested routing layout

### ISSUE THREAD

**Issue by ys2rice2yangsong** [sycamore-rs/sycamore#650]
**Describe the bug**

The routing layout shared data is not updated, while the shared data on other pages is updated

**To Reproduce**

code：
==================================
#[component]
pub fn App<G: Html>(cx: Scope) -> View<G> {
    let  model = create_signal(cx, SystemModel::new());
    
    provide_context_ref(cx, model);

    
    view!{
        cx,
        Router(integration=HistoryIntegration::new(),
        view = |cx, route: &ReadSignal<TopRoute>| {
            
            match route.get().as_ref() {
                //TopRoute::Login => view!{cx, Login{}},
                TopRoute::NotFound => view!{cx, NotFound{}},
                TopRoute::DashboardRoute(dashboard) => {
                    match dashboard {
                        Dashboard::Home => view!{
                            cx,
                            MainLayout{
                                Home{}
                            }
                        },
                        Dashboard::NotFound => view!{cx, NotFound{}}
                    }
                },
                _=> view!{cx, Switch(route=route)}
            }
        })
    }
}

#[component(inline_props)]
fn Switch<'a,G: Html>(cx: Scope<'a>, route: &'a ReadSignal<TopRoute>) -> View<G> {
     view!{
        cx,
        (
            match route.get().as_ref() {
                TopRoute::Login => view!{cx, Login{}},
                _=> view!{cx,}
            }
        )
     }
}

#[component]
pub fn MainLayout<'a, G: Html>(cx: Scope<'a>, children: MainLayoutProps<'a,G>) -> View<G> {
    let systemModel = use_context::<Signal<SystemModel>>(cx);
    let child = children.children.call(cx);
    
    
    
    let systemTheme = systemModel.get().getSystemTheme();
    console!(systemModel.get().is_hide_left.to_string());
    view!{
        cx,
        link(
            rel="stylesheet",
            href = "/css/okadmin.css"
        )
        div(
            class="layui-layout-body"
        ){
            div (
                class=systemTheme
            ){
                Header{}
                LeftSidebar{}
                div(class="content-body"){
                    (child)
                }
            }
            
        }
    }
}

#[component]
pub fn Header<'a, G: Html>(cx: Scope) -> View<G> {
    let mut systemModel = use_context::<Signal<SystemModel>>(cx);
    
    let toogleMenu = move |e| {
        systemModel.modify().is_hide_left = true;
    } 
    ....
}

======================================

**Expected behavior**

**Screenshots**

**Environment**

- Sycamore: [e.g. 0.8.2, master]
- Browser: [e.g. chrome, safari, if applicable]
- OS: [e.g. ubuntu, if applicable]

**Additional context**

**Comment by lukechu10** [comment]
The `view` function passed to `Router` is only called once. You need to put the entire `match` statement inside a `view! { (match ...) }` to make it reactive.
