### ISSUE TITLE
Nested component using string error

### ISSUE THREAD

**Issue by ys2rice2yangsong** [sycamore-rs/sycamore#653]
**Describe the bug**

**To Reproduce**

#[component(inline_props)]
fn T<G:Html>(cx:Scope,title: String, level: i32) -> View<G> {
    let tt = title.clone();

    view!{
        cx,
        (
            if level<5 {
                view!{
                    cx,
                    T(
                        title=tt,
                        level=level+1
                    )
                }
            } else {
                view!{
                    cx,
                    p{
                        (tt)
                    }
                }
            }
        )
    }
}

error info：
cannot move out of `tt_clone`, a captured variable in an `FnMut` closure
`tt_clone` is moved hererustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B0%5D?0#file%3A%2F%2F%2Fhome%2Foem%2Fwww%2Fsycamore%2Fdemo1%2Fsrc%2Fmain.rs)
main.rs(25, 9): captured outer variable
main.rs(26, 5): captured by this `FnMut` closure
main.rs(33, 31): variable moved due to use in closure
main.rs(33, 31): move occurs because `tt_clone` has type `String`, which does not implement the `Copy` trait

**Expected behavior**

**Screenshots**

**Environment**

- Sycamore: [e.g. 0.8.2, master]
- Browser: [e.g. chrome, safari, if applicable]
- OS: [e.g. Windows, if applicable]

**Additional context**

**Comment by lukechu10** [comment]
Where is `tt_clone`? I believe what you want is `title.clone()` inside the inner view. Please reopen if this doesn't solve your issue.
