### ISSUE TITLE
  Nested component click event error

### ISSUE THREAD

**Issue by ys2rice2yangsong** [sycamore-rs/sycamore#654]
**Describe the bug**

**To Reproduce**

#[component(inline_props)]
fn T<G:Html>(cx:Scope,title: String, level: i32) -> View<G> {
    let tt = title.clone();
    let tt_clone = title.clone();
    view!{
        cx,
        (
            if level<5 {
                view!{
                    cx,
                    T(
                        title="afasdf".to_string(),
                        level=level+1
                    )
                }
            } else {
                view!{
                    cx,
                    p(
                        on:click=move |e| {
                            console!(title.clone());
                        }
                    ){
                        (tt)
                    }
                }
            }
        )
    }
}

error  info：
cannot move out of `title`, a captured variable in an `FnMut` closure
`title` is moved hererustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B4%5D?4#file%3A%2F%2F%2Fhome%2Foem%2Fwww%2Fsycamore%2Fdemo1%2Fsrc%2Fmain.rs)
main.rs(24, 23): captured outer variable
main.rs(27, 5): captured by this `FnMut` closure
main.rs(43, 38): variable moved due to use in closure
main.rs(43, 38): move occurs because `title` has type `String`, which does not implement the `Copy` trait

**Expected behavior**

**Screenshots**

**Environment**

- Sycamore: [e.g. 0.8.2, master]
- Browser: [e.g. chrome, safari, if applicable]
- OS: [e.g. Windows, if applicable]

**Additional context**

**Comment by lukechu10** [comment]
You probably want to rebind `tt` inside the else block. This is a Rust error, not a bug with Sycamore.
